name: 🐞 Bug report
description: Report a bug or problem
title: 'bug: '
labels: [ 'bug' ]
body:
  - type: markdown
    attributes:
      value: |
        # ArkCulator Bug Report
        
        Please check [here](https://github.com/AEYCEN/arkCulator/labels/bug) whether there are already tickets for this bug before creating a new one
        All points without the `(optional)` note are mandatory fields

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: On which operating system are you using the executable?
      multiple: false
      options:
        - Windows 11
        - Windows 10
        - Linux
    validations:
      required: true

  - type: dropdown
    id: gameVersion
    attributes:
      label: Game (optional)
      description: For which game did you wanted to calculate?
      multiple: true
      options:
        - "Ark: Survival Evolved"
        - "Ark: Survival Ascended"

  - type: textarea
    attributes:
      label: Error Description
      description: |
        - Describe the error in detail
        - If possible, add steps to reproduce the error (Step 1... Step 2...)
        - Add images and videos where possible
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error logs (optional)
      description: Add error messages from the shell
      render: shell

  - type: textarea
    attributes:
      label: Suggested solution (optional)
      description: If possible, add a possible solution to the error

  - type: textarea
    attributes:
      label: Additional context (optional)
      description: Add additional context here
